"""Add APIConfig model

Revision ID: a004207da1f2
Revises: 
Create Date: 2025-06-30 10:38:12.078165

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a004207da1f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('base_url', sa.String(length=255), nullable=False),
                    sa.Column('secret_key', sa.String(length=255), nullable=False),
                    sa.Column('verify_ssl', sa.Boolean(), nullable=True),
                    sa.Column('is_default', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=255),
                              type_=sa.String(length=255),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
                              existing_type=sa.String(length=128),
                              type_=sa.VARCHAR(length=255),
                              existing_nullable=True)

    op.drop_table('api_configs')
    # ### end Alembic commands ###
